package com.expense_tracker.dto.ai;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "AI Financial Assistant response payload")
public class AiChatResponse {

    @Schema(description = "Natural language response generated by the assistant",
            example = "I've recorded an expense of $35.00 under 'Groceries' for Trader Joe's.")
    private String response;

    @Schema(description = "List of tools executed autonomously during this turn")
    private List<String> executedTools;

    @Schema(description = "Timestamp when the response was processed")
    @Builder.Default
    private LocalDateTime timestamp = LocalDateTime.now();
}
